source 'https://rubygems.org'

gem 'rails', '4.2.0.beta1'
gem 'sqlite3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0.0.beta2'
  gem 'spring'
end

